### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by davemacdo** [davemacdo/composer-diversity#11]
There are still a handful of URLs that don't start with HTTP. That creates a broken link for those composers' sites. This needs to be fixed manually. We should also be sure to use HTTPS when it's available. The best thing to do is go through the sheet and look for all the URLs that are in red. Click through to the site (this will resolve whether it's HTTP or HTTPS), and then copy that _full_ URL back into the spreadsheet. When this is done, I'll pull a fresh copy and commit it to the repo.

**Comment by davemacdo** [comment]
I'm going to close this issue, as it seems as though Rob has fixed most or all of them. I've updated the dataset on the site accordingly. 

_Thanks, Rob!_

**Comment by robdeemer** [comment]
Sweet, thanks! I'm looking at colors right now…

**Comment by robdeemer** [comment]
Gah—can you update the site again? I noticed that the very first composer's link wasn't working and I fixed it. I'm sure people will click on it, so that'd be awkward ;)

**Comment by davemacdo** [comment]
Sure. That’s what happens if you request https and it’s not available. It
happens a lot of somebody removes https for their site or has the
certificate set up incorrectly (which is really easy to do!).



From: Rob Deemer <notifications@github.com> <notifications@github.com>
Reply: davemacdo/composer-diversity
<reply@reply.github.com>
<reply@reply.github.com>
Date: April 30, 2018 at 11:54:57 PM
To: davemacdo/composer-diversity <composer-diversity@noreply.github.com>
<composer-diversity@noreply.github.com>
Cc: David MacDonald <davidjohnmacdonald@gmail.com>
<davidjohnmacdonald@gmail.com>, State change
<state_change@noreply.github.com> <state_change@noreply.github.com>
Subject:  Re: [davemacdo/composer-diversity] URLs (#11)

Gah—can you update the site again? I noticed that the very first composer's
link wasn't working and I fixed it. I'm sure people will click on it, so
that'd be awkward ;)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/davemacdo/composer-diversity/issues/11#issuecomment-385593375>,
or mute the thread

**Comment by davemacdo** [comment]
Reopening.

Many URLs are in the database as https. We may need to roll back to the previous state of the DB and then return to the initial issue, above.

**Comment by robdeemer** [comment]
Done. I live & learn :) Sorry for the lameness!

**Comment by robdeemer** [comment]
(hopefully) done!

**Comment by davemacdo** [comment]
Alright. I'll close the issue and open new ones for the genre and demographic database changes.

**Comment by robdeemer** [comment]
Thanks...and when you get a chance, can you re-up the content so I can confirm the changes I made work? Thanks!

————————
Dr. Rob Deemer
Head of Music Composition & Assistant to the President
American Council on Education Fellow (2016-2017)
School of Music, State University of New York at Fredonia

Chair, NYSSMA Composition & Improvisation Committee
Chair-Elect, NAfME Council of Music Composition

Composer-in-Residence, Buffalo Chamber Players
Composer-in-Residence, Harmonia Chamber Singers

3162 Mason Hall • Fredonia, NY 14063 • (716) 673-3133
e-mail: deemer@fredonia.edu • web: www.robdeemer.com
