### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by davemacdo** [davemacdo/composer-diversity#13]
This is kind of a meta-issue, but I think this is as good a place as any to put it. 

I've gone through and marked each of the issues with the release that I think it should correspond with (Milestones). Everything that is marked 1.0 is what I think we need to have or fix before the initial release. If you (Rob) or anybody disagrees with the Milestones I've assigned the Issues, please let me know. 

Once we've knocked out the remaining issues assigned to the 1.0 Milestone, I think we're good to release. 

Thoughts? (I'll close this issue upon consensus.)

**Comment by robdeemer** [comment]
I like this idea. We have purchased domain names for this and my wife Lori is doing the work to make those happen…I'll probably put her in contact with you to let you two get that squared away soon. I will also probably let a few people put it through it's paces before sending it out into the world, but I can't believe it's at the level that it is. Thanks so much, David!

**Comment by davemacdo** [comment]
It's my pleasure. Let me know if I need to do anything to make the domain names connect on this end. A plain-ol' redirect is fine, but I also know it's possible to set up [custom domains](https://help.github.com/articles/using-a-custom-domain-with-github-pages/).

I'm hoping that once we launch, some other web-dev nerds see it and are interested in contributing. I'm a total self-taught amateur at this stuff, and GitHub is built for collaboration. I'm hoping that by using issues and milestones in systematic way, I can help keep things organized if anybody else wants to contribute.
