### ISSUE TITLE
blurb

### ISSUE THREAD

**Issue by robdeemer** [davemacdo/composer-diversity#17]
Can we create a blurb such as the Wikipedia link (I got that from posting the link in FB) that will come up in a link on FB and Twitter? Or can we create an image that will come up with those posts?

Such as:
"The Composer Diversity Database is a free online resource for conductors, performers, presenters, educators, and researchers."

![wiki](https://user-images.githubusercontent.com/38842773/39477757-3a7e58de-4d2e-11e8-95ae-14790de5a7de.jpg)

**Comment by davemacdo** [comment]
Yes. I haven’t done one of those before, but I’m pretty sure I know how it’s done.

**Comment by davemacdo** [comment]
Ok. It was just as easy as I expected! Here is the Twitter card: 

<img width="534" alt="screen shot 2018-05-01 at 4 07 38 pm" src="https://user-images.githubusercontent.com/6425544/39491341-092e1dba-4d5a-11e8-90a8-29338158ea27.png">

Here are two options for the Facebook card, one is the small square; the other is the big card. I could go either way. 

<img width="534" alt="screen shot 2018-05-01 at 4 07 38 pm" src="https://user-images.githubusercontent.com/6425544/39491368-2f8ade9e-4d5a-11e8-9037-9cd5401285b7.png">

<img width="559" alt="screen shot 2018-05-01 at 4 08 18 pm" src="https://user-images.githubusercontent.com/6425544/39491375-33490efc-4d5a-11e8-90ad-e78b4e4edceb.png">

**Comment by robdeemer** [comment]
Let’s go big for Facebook :)

————————
Dr. Rob Deemer
Head of Music Composition & Assistant to the President
American Council on Education Fellow (2016-2017)
School of Music, State University of New York at Fredonia

Chair, NYSSMA Composition & Improvisation Committee
Chair-Elect, NAfME Council of Music Composition

Composer-in-Residence, Buffalo Chamber Players
Composer-in-Residence, Harmonia Chamber Singers

3162 Mason Hall • Fredonia, NY 14063 • (716) 673-3133
e-mail: deemer@fredonia.edu • web: www.robdeemer.com
