### ISSUE TITLE
Badges on composer cards

### ISSUE THREAD

**Issue by robdeemer** [davemacdo/composer-diversity#2]
I'm thinking that we can forgo the sun/moon emoji (which are small) because those that are dead will have a death date after their name, so the emoji are redundant. Thanks!

**Comment by davemacdo** [comment]
Agreed. They didn't match well with the other badges, either. I've just removed them.

**Comment by robdeemer** [comment]
I just got done speaking with Alex Shapiro and we came to the conclusion that it'd be fine if all of the badges go away! It'll help with de-cluttering the page, it may help with spacing, and if someone is looking for a different or specific filter, all they have to do is click the button. Thoughts?

**Comment by davemacdo** [comment]
I kind of like having the extra information. I kind of like seeing what else might be available from the same composer. What about just keeping the genre badges and removing the gender and demographic badges?

**Comment by robdeemer** [comment]
Let's try it and see how it works 👍

**Comment by davemacdo** [comment]
Now it's only showing genre/medium badges, and they're all the same color. Thoughts?

**Comment by robdeemer** [comment]
Let's put back the gender badges so folks don't have to guess (some names are tricky that way).

**Comment by robdeemer** [comment]
This actually answers another question I just sent about a key. Rollover is great…but we should provide instructions on the page that that's in effect (otherwise folks might not realize it's there)

**Comment by davemacdo** [comment]
I'm going to mark this as closed and deal with the badge "legend" in [this issue](https://github.com/davemacdo/composer-diversity/issues/6).
