### ISSUE TITLE
Add Southeast Asia to demographic records

### ISSUE THREAD

**Issue by davemacdo** [davemacdo/composer-diversity#20]
Add to the database first, then adjust app.

**Comment by robdeemer** [comment]
Such logic...heh

————————
Dr. Rob Deemer
Head of Music Composition & Assistant to the President
American Council on Education Fellow (2016-2017)
School of Music, State University of New York at Fredonia

Chair, NYSSMA Composition & Improvisation Committee
Chair-Elect, NAfME Council of Music Composition

Composer-in-Residence, Buffalo Chamber Players
Composer-in-Residence, Harmonia Chamber Singers

3162 Mason Hall • Fredonia, NY 14063 • (716) 673-3133
e-mail: deemer@fredonia.edu • web: www.robdeemer.com

**Comment by davemacdo** [comment]
Done.
