### ISSUE TITLE
Clear Button & Footer

### ISSUE THREAD

**Issue by robdeemer** [davemacdo/composer-diversity#22]
Hi David,

I've received a couple of suggestions from Andrew Martin Smith and Jamie Leigh Sampson:
1) Could there be a "clear" button that's reachable no matter where you are so you can flush out any search that is currently in use?
2) Could there be a footer that not only allows for a bit of padding on the bottom but that could include that "clear" button? 

Thanks!

-Rob

**Comment by davemacdo** [comment]
I think a "clear all filters" button is a good idea. I'll add it to the filter options. I'm happy to add some space at the bottom of the page, but I'd rather not put anything important or functional there, since it's going to be so far away most of the time.

**Comment by davemacdo** [comment]
I've added the clear button to the bottom of the filter options panel and increased the padding at the bottom of the list of cards. I'm going to close the issue, but I'm happy to reopen if you think it should look or behave differently.
