### ISSUE TITLE
Added text

### ISSUE THREAD

**Issue by robdeemer** [davemacdo/composer-diversity#28]
Let's add the following under the 2nd paragraph on the "About the project" page:

Note: The Medium/Subgenre section was added much later in the database construction process and it is not yet complete. Therefore, there are a number of composers who have written works for specific subgenres who may not yet come up in searches. Please be patient as we complete this sizable task and feel free to use the form below to alert us to any adjustments that may need to be made.

**Comment by davemacdo** [comment]
Done.
