### ISSUE TITLE
Search total

### ISSUE THREAD

**Issue by robdeemer** [davemacdo/composer-diversity#3]
I love the fact that there are numbers in parentheses after each of the checkboxes. Is there a way to show a search total? Let's say if I click living black wind band composers who are women, the search title would show how many are there within that search function? Thanks, David!

**Comment by davemacdo** [comment]
I thought about trying to do that. It wouldn't be easy with the way I have it currently implemented, but there's got to be a good way to do that. It's a fantastic idea. I'll definitely look into it.

**Comment by davemacdo** [comment]
There is now a search total displayed below the "clear filters" button.
