### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by robdeemer** [davemacdo/composer-diversity#4]
I wanted to just let you know that I can't thank you enough for bringing this project to the next level. I will be looking at our options in terms of getting grants for this project, so I hope that this will not be a volunteer endeavor forever. I also understand that you've got other stuff going on, so please don't take my spate of ideas as me being impatient…I just figured I'd get them to you when I think of them.

-Rob

**Comment by davemacdo** [comment]
My pleasure! Thanks for all the work you've done to compile the data and being so generous with sharing it!
