### ISSUE TITLE
Color Scheme/Fonts/Overall Visuals

### ISSUE THREAD

**Issue by robdeemer** [davemacdo/composer-diversity#5]
- What options do we have in terms of colors of fonts and colors of background? I'm not sure about the green & red…
- Do we have options in terms of the fonts in the title? The overall font choice is great!
- Alex mentioned (and I agree) that a grid or some type of graphic delineation between the names would be handy to see the organization.
- Can we bring the reduce the size of the search bar? It looks bigger than the size of the names in the database and it might make sense to have those be equal in size.

**Comment by davemacdo** [comment]
I've just made a small update to address some of this: 

- cards now have a slightly darker background than the rest of the page, so there's a separation without drawing a bunch of rectangles
- search box is less Fischer Pricey in size

I haven't had time to think about type and color yet. I'll keep this issue open for now.

**Comment by robdeemer** [comment]
I like the cards! Can we bump the size of the title up a bit?

**Comment by robdeemer** [comment]
As you think about colors, I'm wondering if we should go with some type of blue since that's a traditional color for links, but it could be still from the pastel set you're working in. I'm also wondering if we need to make sure that the colors we pick won't make it hard for folks with color blindness to read :)

**Comment by davemacdo** [comment]
- Yes. Title size is going up, especially on large displays. I think the current size is good for phones. 
- I'm playing around now with a blue-dominant palette. Let me know what you think. I'm not a designer. 
- On visual accessibility, I use a browser extension to simulate the most common types of color deficiency. I'm trying to focus more on shapes for visual distinctions. 

Here's something resembling a design comp from a non-designer: 

![composer-diversity site sketch](https://user-images.githubusercontent.com/6425544/39447568-2df0f480-4c90-11e8-82e1-3c5419bcce17.png)

Thoughts?

**Comment by davemacdo** [comment]
This is the extension I'm using if you want to try it: 

[NoCoffee](https://chrome.google.com/webstore/detail/nocoffee/jjeeggmbnhckmgdhmgdckeigabjfbddl?hl=en)

And I forgot to mention that I didn't put the emoji in the image above, but I intend to keep them. I kind of like them.

**Comment by robdeemer** [comment]
I like the idea of a white background with the blue boxes and the blue-to-red fonts. Is that possible? If not, what you have in your second send is good…the other one is just a touch too dark.

Also, can we delineate the checkboxes a horizontal color around the entire section?

**Comment by davemacdo** [comment]
Take a look and tell me what you think. I like it.

**Comment by robdeemer** [comment]
Overall it looks great! I'm currently a little nervous about the blue links on the blue boxes…the lack of contrast is troubling. Can we go with gold backgrounds (boxes) and keep the blue links?

**Comment by robdeemer** [comment]
Grr…now the more I look at it, I'm not sure if it's the blue backgrounds or the color of the linked names. They're so close…unless you can come up with a link color that pops a bit more with out clashing, hold off on this one for a bit. I'm afraid the gold is going to be too light and the blue does section the whole thing off nicely.

I apologize for being one of "those" guys when it comes to this…trying not to be too picky. It does look damn good!

**Comment by davemacdo** [comment]
No worries. I played around with it a bit and discovered that gold also made the contrast with the badges too low. I have a compromise of an even lighter shade of blue for the cards, and a teensy bit darker gold for the badges. 

It performs much better in NoCoffee's contrast loss vision simulator. 

And for the record, tweaking colors is easy. I'm pretty organized with them. They just live in a [single file here](https://github.com/davemacdo/composer-diversity/blob/master/src/_vars.scss). I can change the values any time. 

If this works for you, I'll close the issue.

**Comment by robdeemer** [comment]
Done & done. Looks great!!!

**Comment by davemacdo** [comment]
One step closer!

**Comment by robdeemer** [comment]
Hi Dave,

After looking at this for a while, can we change the rollover color on the links to the red color that you have above? The bright light blue you currently have just isn't working for me (too many different shades of blue?)…thanks for letting me live with it for a while.

**Comment by robdeemer** [comment]
Option A it is...let’s live with it and see how it feels!

————————
Dr. Rob Deemer
Head of Music Composition & Assistant to the President
American Council on Education Fellow (2016-2017)
School of Music, State University of New York at Fredonia

Chair, NYSSMA Composition & Improvisation Committee
Chair-Elect, NAfME Council of Music Composition

Composer-in-Residence, Buffalo Chamber Players
Composer-in-Residence, Harmonia Chamber Singers

3162 Mason Hall • Fredonia, NY 14063 • (716) 673-3133
e-mail: deemer@fredonia.edu • web: www.robdeemer.com

**Comment by davemacdo** [comment]
Looking at this as I tested the new data stuff today, I'm liking it a lot better now that the active point on the screen is more different from the rest of the page. Good call, Rob. 

Closing for now.
