### ISSUE TITLE
Tags - capitalization

### ISSUE THREAD

**Issue by robdeemer** [davemacdo/composer-diversity#6]
- There's currently some tags (Cha, Or) that start with capital letters and others (sq, bl) that don't. Let's have them all start with capitals to be consistent.
- Alex asked about a "key" up top so folks could see quickly what the tags corresponded to. Is there any easy way to do this? Maybe a separate "Orchestra (Or) (1869)"?

**Comment by davemacdo** [comment]
- Yes. I'll make them all align. 
- Good idea! I'll put a badge next to the full name in the filter list. That's the perfect place for it.

**Comment by robdeemer** [comment]
Love that idea about the badge next to the full name!

**Comment by davemacdo** [comment]
- Badges are (I think) now consistently capitalized. Let me know if you spot any that aren't. 
- Badges that show on the composer "cards" now also show next to the toggles. I think it's pretty.

**Comment by davemacdo** [comment]
Just pulled fresh data from the sheet and capitalized everything in the demographics. Let me know if that looks right to you, or if you want the other labels to be capitalized. (I'm reopening this issue to track this.)
