### ISSUE TITLE
Filter based on in or outside USA

### ISSUE THREAD

**Issue by robdeemer** [davemacdo/composer-diversity#7]
Is there any relatively painless way to do a search by location? Either by country or by state? Could it be something that you type in and it brings up everyone in that place? I could type in Chicago and everyone there comes up? Or USA? 

See what happens when I start going down the rabbit hole?

**Comment by davemacdo** [comment]
Right now, the search field is _only_ tied to the name, but it could also be tied to location. 

I was thinking about US/non-US filters, which would be a lot coarser, but maybe get you most of the way to where you'd want to go.

**Comment by robdeemer** [comment]
That's a start…can we get two checkboxes for now (USA/Non-USA)?

**Comment by davemacdo** [comment]
That's totally reasonable. Shouldn't be too difficult to implement. You did a great job keeping the data consistent on abbreviating USA. I'll consider that the scope of this issue and move it to the 1.0 milestone.

**Comment by robdeemer** [comment]
Let's try this language: "Based in USA" "Based outside of USA"

**Comment by davemacdo** [comment]
With (I think) a clever bit of code, the USA filter is now functional.
